# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_tag_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headtag',
            options={'ordering': ('-created_date',)},
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
