# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily_tag_app', '0003_auto_20170629_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.IntegerField()),
                ('head_tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='view_count', to='daily_tag_app.HeadTag')),
            ],
        ),
    ]
