# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_tag_app', '0004_viewrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='headtag',
            name='page_view_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
